apiVersion: v1
kind: Pod
metadata:
  labels:
    run: full-app
  name: full-app
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}
  containers:
  - image: bharatsantani/web-app
    name: web-app
    resources: {}
    volumeMounts:
    - name: shared-volume
      mountPath: /var/log/shared-volume
  - image: nginx
    name: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html
    resources: {}
  