apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-app
  name: web-app
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}
  containers:
  - image: bharatsantani/web-app
    name: web-app
    resources: {}
    volumeMounts:
    - name: shared-volume
      mountPath: /var/log/shared-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always